# Generated by Django 3.2.23 on 2023-12-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone_no', models.CharField(max_length=45)),
                ('adress', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=45)),
                ('house_name', models.CharField(db_column='house name', max_length=45)),
                ('landmark', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
    ]
