# Generated by Django 3.2.23 on 2023-12-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('mesherment_id', models.AutoField(primary_key=True, serialize=False)),
                ('mesherments', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'measurements',
                'managed': False,
            },
        ),
    ]
