# Generated by Django 3.2.23 on 2023-12-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designers',
            fields=[
                ('designers_id', models.AutoField(primary_key=True, serialize=False)),
                ('designers_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone_no', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'designers',
                'managed': False,
            },
        ),
    ]
